### PR TITLE
Avoid ArgumentException when deleting users

### PR DESCRIPTION
**Pull request by jbinder**
Allows users that have no email or phone number to be deleted.

### CODE REVIEW

**Comment by mfidemraizer** [comment]
Hey, @jbinder 

First of all, thank you for using your effort to improve this project.

You're right, it should allow users with and without an *email* and/or *phone number*.

Please review the comment I've made to your source code concerning a change from *null checking* to `!string.IsNullOrEmpty`. If you change those null checks with `!string.IsNullOrEmpty` I'll merge your change, and after that, I'll build a new NuGet package version.

Thank you again and I'll look forward for your updated pull request!

**Comment by jbinder** [comment]
Hi,

sure thing, thanks a lot!
I just came across an issue when retrieving users by an ID which does not exist, could you please include this one as well in the package release?

Thanks!

**Comment by mfidemraizer** [comment]
@jbinder 

Hi again!

Thanks for your effort. Today will be impossible that I could take a look at the code, but I've checked it and it seems fine.

I expect to merge and create a new NuGet package to publish it within the next days (I believe it'll be this weekend...).

**Comment by jbinder** [comment]
Great, thanks!

**Comment by mfidemraizer** [comment]
@jbinder I've already pushed the NuGet package (1.0.4). Can you check that it works as expected in your scenario? It should work fine since it includes your changes...

PD: It would be great having a good test suite...

**Comment by jbinder** [comment]
@mfidemraizer It works, thanks! Agreed, tests would be very helpful.

**Pull request merged**
